theme: jekyll-theme-architect

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
include:
  - The Coders Computer.md
  - Learning Markdown.md
  - Revisions and the Cloud.md
  - README.md

